# Generated by Django 4.2.5 on 2023-11-03 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("skill1", models.CharField(max_length=50)),
                ("skill2", models.CharField(max_length=50)),
                ("skill3", models.CharField(max_length=50)),
                ("experience", models.CharField(max_length=50)),
                ("interests", models.CharField(max_length=50)),
                ("goals", models.CharField(max_length=50)),
            ],
        ),
    ]
